templates:
  path: favorites-default.odt
  images:
    - zipPath: 'Pictures/1001AF2C00001B58000013884478CBA59A4FBD23.svg'
      property: [settings, themes, 0, logo_url]
    - zipPath: 'Pictures/10001E83000014C6000014C6A9CA85DB240426D5.svg'
      property: [globals, favorites_qrcode_url]
