services:
  carbone:
    build: carbone-docker
    image: ghcr.io/teritorio/elasa-export-carbone:master
    environment:
      - DEBUG=carbone:*
    volumes:
      - ./templates:/home/node/carbone-api/templates:ro
      - ./carbone-docker/index.js:/home/node/carbone-api/index.js
      - ./carbone-docker/images.js:/home/node/carbone-api/images.js
    restart: unless-stopped

  api:
    build: api
    image: ghcr.io/teritorio/elasa-export-api:master
    environment:
      - CONFIG=/data/config.yaml
      # - RACK_ENV=production
      - CARBONE_URL=http://carbone:3030
      - CACHE=cache
      - API_URL=${API_URL:-}
      - QR_SHORTENER_URL=${QR_SHORTENER_URL:-}
      - LANGS=${LANGS:-}
    volumes:
      - ./config.yaml:/data/config.yaml
      # - ./api/api.rb:/srv/app/api.rb
      # - ./api/favorites.rb:/srv/app/favorites.rb
    depends_on:
      - carbone
    ports:
      - "4567:4567"
    restart: unless-stopped

volumes:
  cache:
