version: '3'

services:
  carbone:
    build: carbone-docker
    image: ghcr.io/teritorio/elasa-export-carbone:master
    environment:
      - DEBUG=carbone:*
    volumes:
      - ./templates:/home/node/carbone-api/templates:ro
      - ./carbone-docker/index.js:/home/node/carbone-api/index.js
      - ./carbone-docker/images.js:/home/node/carbone-api/images.js
    restart: unless-stopped

  api:
    build: api
    image: ghcr.io/teritorio/elasa-export-api:master
    environment:
      - CONFIG=/data/config.yaml
      # - RACK_ENV=production
    volumes:
      - ./config.yaml:/data/config.yaml
      - ./api:/srv/app
    depends_on:
      - carbone
    ports:
      - "4567:4567"
    restart: unless-stopped

volumes:
  cache:
